### ISSUE TITLE
error import fromBlob from './fromBlob.js';

### ISSUE THREAD

**Issue by rubensflinco** [alefduarte/image-resize-compress#9]
someone help me I'm having this error, here's an excerpt of my code:

        const imageResizeCompress = require('image-resize-compress');

        let comprimirImg = await imageResizeCompress.fromBlob(buffer, 50, 1920);

error:

          import fromBlob from './fromBlob.js'
          ^^^^^^
          
          SyntaxError: Cannot use import statement outside a module
              at wrapSafe (internal/modules/cjs/loader.js:1053:16)
              at Module._compile (internal/modules/cjs/loader.js:1101:27)
              at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
              at Module.load (internal/modules/cjs/loader.js:985:32)
              at Function.Module._load (internal/modules/cjs/loader.js:878:14)
              at Module.require (internal/modules/cjs/loader.js:1025:19)
              at require (internal/modules/cjs/helpers.js:72:18)
              at Object.<anonymous> (F:\RubensFlinco-PC\Documents\Github\IAB-Back-End\routes\upload.js:12:29)
              at Module._compile (internal/modules/cjs/loader.js:1137:30)
              at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
              at Module.load (internal/modules/cjs/loader.js:985:32)
              at Function.Module._load (internal/modules/cjs/loader.js:878:14)
              at Module.require (internal/modules/cjs/loader.js:1025:19)
              at require (internal/modules/cjs/helpers.js:72:18)
              at Object.<anonymous> (F:\RubensFlinco-PC\Documents\Github\IAB-Back-End\server.js:42:20)
              at Module._compile (internal/modules/cjs/loader.js:1137:30)
          [nodemon] app crashed - waiting for file changes before starting...

**Comment by alefduarte** [comment]
I don't know if you have found the solution by now, but check whether your package.json "type" key is set to "module"
```js
// package.json
{
  "type": "module"
}

**Comment by alefduarte** [comment]
Fixed with #17
